"""add timezone and start-of-day to user

Revision ID: 517c61e085a2
Revises: cd3b1ad8c50b
Create Date: 2020-09-25 00:16:53.532597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517c61e085a2'
down_revision = 'cd3b1ad8c50b'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('user', sa.Column(
        'start_of_day', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column(
        'timezone', sa.String(length=64), nullable=True))
    sa.orm.Session(bind=op.get_bind()).commit()

    # batch mode is needed to support sqlite, which doesn't support ALTER COLUMN
    with op.batch_alter_table('user') as batch_op:
        batch_op.execute("UPDATE user SET start_of_day = 2")
        batch_op.execute("UPDATE user SET timezone = 'Europe/Warsaw'")

        batch_op.alter_column('start_of_day', nullable=False)
        batch_op.alter_column('timezone', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'timezone')
    op.drop_column('user', 'start_of_day')
    # ### end Alembic commands ###
